name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://ip4035230069.mobgslb.tbcache.com/Firmware/Flyme/meizu17_Pro/8.1.2.1/cn/20200515190836/94f35658/update.zip?ali_redirect_domain=firmware.meizu.com&ali_redirect_ex_ftag=058eb30c77c2a42ad6192a43a0820b5be4b207b53c8c8a5b&ali_redirect_ex_tmining_ts=1591439271&ali_redirect_ex_tmining_expire=3600&ali_redirect_ex_hot=100
  ROM_NAME: Flyme
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate Aonly GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z GSI
         run: |
           7za a -t7z -r ErfanGsi.7z ErfanGSIs/output/*
       
       - name: Upload GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ErfanGsi.7z
           
#       - name: Make clean
#         run: sudo rm -rf ErfanGSIs/output/*
         
#       - name: Download Stock Rom & Generate AB GSI
#         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

#       - name: 7z AB GSI
#         run: |
#           7za a -t7z -r AB_GSI.7z ErfanGSIs/output/*

#       - name: Upload AB GSI to WeTransfer
#         run: |
#              curl -sL https://git.io/file-transfer | sh
#              ./transfer wet AB_GSI.7z
         
            
